name: Piletivaht

on:
  schedule:
    - cron: '0 6 * * 5,6'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: pip install requests

      - name: Run script
        run: python check.py
